@startuml 
left to right direction

actor User as "User"

rectangle "Source Code Pert4" {
    usecase "Choice Menu" as menu
    usecase "Masukkan Angka Pertama" as input1
    usecase "Masukkan Angka Kedua" as input2
    usecase "Call void tambah" as tambah
    usecase "Call void kurang" as kurang
    usecase "Call void bagi" as bagi
    usecase "Call void kali" as kali
    usecase "Show Result" as hasil
    usecase "Exit Program" as exit
}

User --> menu

menu --> tambah : pilih tambah
tambah --> input1
input1 --> input2
input2 --> hasil
hasil --> menu

menu --> kurang : pilih kurang
kurang --> input1
input1 --> input2
input2 --> hasil
hasil --> menu

menu --> bagi : pilih bagi
bagi --> input1
input1 --> input2
input2 --> hasil
hasil --> menu

menu --> kali : pilih kali
kali --> input1
input1 --> input2
input2 --> hasil
hasil --> menu

menu --> exit : pilih keluar
exit --> menu : kembali ke menu awal

@enduml
