@startuml pert7
start
:initialize variable;
while (true) is (true)
    :display menu utama
    1. Makanan
    2. Minuman
    3. Exit;
    :get user input(pilih);
    if (pilih == 1) then (case Makanan)
        :display menu makanan
         1. Ayam Goreng
         2. Ketoprak
         3. Nasi Goreng;
        :get user input(pilih_Makan);
        if (pilih_Makan == '1') then (case ayam goreng)
            :initialize variable;
            :display "Anda memilih Ayam Goreng";
            :get jumlah pesanan;
            :hitung total harga (jumlah * harga_ayam_goreng);
            :display "Total harga: Rp. [total_harga]";
        else if (pilih_Makan == '2') then (case ketoprak)
            :initialize variable;
            :display "Anda memilih Ketoprak";
            :get jumlah pesanan;
            :hitung total harga (jumlah * harga_ketoprak);
            :display "Total harga: Rp. [total_harga]";
        else if (pilih_Makan == '3') then (case nasi goreng)
            :initialize variable;
            :display "Anda memilih Nasi Goreng";
            :get jumlah pesanan;
            :hitung total harga (jumlah * harga_nasi_goreng);
            :display "Total harga: Rp. [total_harga]";
        else if (pilih_Makan == '4') then (case kembali)
            :goto menu;
        else
            :display "pilihan salah!";
        endif
        :kembali ke menu utama;


        

    else if (pilih == 2) then (case Minuman)
        :display menu minuman
        1. Jus Mangga
        2. Coffee
        3. Teh Jus;
        :get user input(pilih_Minum);
        if (pilih_Minum == '1') then (case jus mangga)
            :initialize variable;
            :display "Anda memilih Jus Mangga";
            :get jumlah pesanan;
            :hitung total harga (jumlah * harga_jus_mangga);
            :display "Total harga: Rp. [total_harga]";
        else if (pilih_Minum == '2') then (case coffee)
            :initialize variable;
            :display "Anda memilih Coffee";
            :get jumlah pesanan;
            :hitung total harga (jumlah * harga_coffee);
            :display "Total harga: Rp. [total_harga]";
        else if (pilih_Minum == '3') then (case teh jus)
            :initialize variable;
            :display "Anda memilih Teh Jus";
            :get jumlah pesanan;
            :hitung total harga (jumlah * harga_teh_jus);
            :display "Total harga: Rp. [total_harga]";
        else if (pilih_Minuman == '4') then (case kembali)
            :goto menu;
        else
            :display "pilihan salah!";
        endif
        :kembali ke menu utama;
        
    else if (pilih == 3) then (case 3)
        :display "EXIT";
        break
    else
        :display "pilihan salah!";
    endif
endwhile (false)
:display "EXIT";
stop
@enduml
